/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as VaultRouteImport } from './routes/_vault'
import { Route as VaultIndexRouteImport } from './routes/_vault/index'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as ApiNotesRouteImport } from './routes/api/notes'
import { Route as VaultNewRouteImport } from './routes/_vault/new'
import { Route as ApiNotesIdRouteImport } from './routes/api/notes.$id'
import { Route as VaultNotesIdRouteImport } from './routes/_vault/notes/$id'
import { Route as ApiNotesIdRenderRouteImport } from './routes/api/notes.$id.render'

const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultRoute = VaultRouteImport.update({
  id: '/_vault',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultIndexRoute = VaultIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => VaultRoute,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotesRoute = ApiNotesRouteImport.update({
  id: '/api/notes',
  path: '/api/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultNewRoute = VaultNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => VaultRoute,
} as any)
const ApiNotesIdRoute = ApiNotesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiNotesRoute,
} as any)
const VaultNotesIdRoute = VaultNotesIdRouteImport.update({
  id: '/notes/$id',
  path: '/notes/$id',
  getParentRoute: () => VaultRoute,
} as any)
const ApiNotesIdRenderRoute = ApiNotesIdRenderRouteImport.update({
  id: '/render',
  path: '/render',
  getParentRoute: () => ApiNotesIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof VaultIndexRoute
  '/mcp': typeof McpRoute
  '/new': typeof VaultNewRoute
  '/api/notes': typeof ApiNotesRouteWithChildren
  '/api/search': typeof ApiSearchRoute
  '/notes/$id': typeof VaultNotesIdRoute
  '/api/notes/$id': typeof ApiNotesIdRouteWithChildren
  '/api/notes/$id/render': typeof ApiNotesIdRenderRoute
}
export interface FileRoutesByTo {
  '/mcp': typeof McpRoute
  '/new': typeof VaultNewRoute
  '/api/notes': typeof ApiNotesRouteWithChildren
  '/api/search': typeof ApiSearchRoute
  '/': typeof VaultIndexRoute
  '/notes/$id': typeof VaultNotesIdRoute
  '/api/notes/$id': typeof ApiNotesIdRouteWithChildren
  '/api/notes/$id/render': typeof ApiNotesIdRenderRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_vault': typeof VaultRouteWithChildren
  '/mcp': typeof McpRoute
  '/_vault/new': typeof VaultNewRoute
  '/api/notes': typeof ApiNotesRouteWithChildren
  '/api/search': typeof ApiSearchRoute
  '/_vault/': typeof VaultIndexRoute
  '/_vault/notes/$id': typeof VaultNotesIdRoute
  '/api/notes/$id': typeof ApiNotesIdRouteWithChildren
  '/api/notes/$id/render': typeof ApiNotesIdRenderRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/mcp'
    | '/new'
    | '/api/notes'
    | '/api/search'
    | '/notes/$id'
    | '/api/notes/$id'
    | '/api/notes/$id/render'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/mcp'
    | '/new'
    | '/api/notes'
    | '/api/search'
    | '/'
    | '/notes/$id'
    | '/api/notes/$id'
    | '/api/notes/$id/render'
  id:
    | '__root__'
    | '/_vault'
    | '/mcp'
    | '/_vault/new'
    | '/api/notes'
    | '/api/search'
    | '/_vault/'
    | '/_vault/notes/$id'
    | '/api/notes/$id'
    | '/api/notes/$id/render'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  VaultRoute: typeof VaultRouteWithChildren
  McpRoute: typeof McpRoute
  ApiNotesRoute: typeof ApiNotesRouteWithChildren
  ApiSearchRoute: typeof ApiSearchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_vault': {
      id: '/_vault'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof VaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_vault/': {
      id: '/_vault/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof VaultIndexRouteImport
      parentRoute: typeof VaultRoute
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notes': {
      id: '/api/notes'
      path: '/api/notes'
      fullPath: '/api/notes'
      preLoaderRoute: typeof ApiNotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_vault/new': {
      id: '/_vault/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof VaultNewRouteImport
      parentRoute: typeof VaultRoute
    }
    '/api/notes/$id': {
      id: '/api/notes/$id'
      path: '/$id'
      fullPath: '/api/notes/$id'
      preLoaderRoute: typeof ApiNotesIdRouteImport
      parentRoute: typeof ApiNotesRoute
    }
    '/_vault/notes/$id': {
      id: '/_vault/notes/$id'
      path: '/notes/$id'
      fullPath: '/notes/$id'
      preLoaderRoute: typeof VaultNotesIdRouteImport
      parentRoute: typeof VaultRoute
    }
    '/api/notes/$id/render': {
      id: '/api/notes/$id/render'
      path: '/render'
      fullPath: '/api/notes/$id/render'
      preLoaderRoute: typeof ApiNotesIdRenderRouteImport
      parentRoute: typeof ApiNotesIdRoute
    }
  }
}

interface VaultRouteChildren {
  VaultNewRoute: typeof VaultNewRoute
  VaultIndexRoute: typeof VaultIndexRoute
  VaultNotesIdRoute: typeof VaultNotesIdRoute
}

const VaultRouteChildren: VaultRouteChildren = {
  VaultNewRoute: VaultNewRoute,
  VaultIndexRoute: VaultIndexRoute,
  VaultNotesIdRoute: VaultNotesIdRoute,
}

const VaultRouteWithChildren = VaultRoute._addFileChildren(VaultRouteChildren)

interface ApiNotesIdRouteChildren {
  ApiNotesIdRenderRoute: typeof ApiNotesIdRenderRoute
}

const ApiNotesIdRouteChildren: ApiNotesIdRouteChildren = {
  ApiNotesIdRenderRoute: ApiNotesIdRenderRoute,
}

const ApiNotesIdRouteWithChildren = ApiNotesIdRoute._addFileChildren(
  ApiNotesIdRouteChildren,
)

interface ApiNotesRouteChildren {
  ApiNotesIdRoute: typeof ApiNotesIdRouteWithChildren
}

const ApiNotesRouteChildren: ApiNotesRouteChildren = {
  ApiNotesIdRoute: ApiNotesIdRouteWithChildren,
}

const ApiNotesRouteWithChildren = ApiNotesRoute._addFileChildren(
  ApiNotesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  VaultRoute: VaultRouteWithChildren,
  McpRoute: McpRoute,
  ApiNotesRoute: ApiNotesRouteWithChildren,
  ApiSearchRoute: ApiSearchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
